### PR TITLE
first draft of ability filters

### PR DESCRIPTION
**Pull request by jburleigh1**
Hey,

You guys might want to test this with your app first, but it shouldn't break anything. It adds a dynamic ability filter to the ability page, which you can use to drill down into more specific abilities. 

I think the placement of the filter on desktop / tablet is fine, on mob it's just lumped at the top above all the abilities. It might be a better idea to hide the filters off canvas on mob, maybe behind a hamburger. Let me know what you think.
d23376b862ee69b1423ac025602db9da

### CODE REVIEW

**Comment by tehsquidge** [comment]
Thanks very much for the contribution! I believe you've forgotten to add the main.js file into the commit. Add that and I'll merge it in.

- Liam

**Comment by jburleigh1** [comment]
done! Apparently it was ignored via .gitignore, but I don't see a rule in there ignoring the file. I added it with -f. I also cleaned some stuff up this morning, and removed the character attribute fields, saving them for another feature branch :)

**Comment by jburleigh1** [comment]
added missing file... again.

**Comment by tehsquidge** [comment]
Merged! Thanks very much!

**Pull request merged**
